Fecha: 28/04/2026
Retome los ejercicios anteriores 

-Tome un corpus de 1800 a 2000 palabras, después de pre-procesar los datos, aplique un método de vectorización, reduzca dimensión y normalice los vectores.

- Realizar el siguiente ventaneo:
    -> Doc: Hola Mundo, ESCOM es un lugar donde dan los buenos días.
- Suponga los vectores 

|                                               |                     |
|-----------------------------------------------|---------------------|
|[1,0.3,0.5] [0.7, 0.5, 0.3] [0.4, 0.3, 0.6]    | Hola , Mundo, ESCOM |
|[0.1, 0.2, 0.3] [0.4, 0.1, 0.4] [0.2, 0.1, 0.2]| es lugar donde      |

- A través de una red neuronal arme la siguiente matriz, y entrene

|       X         |   -->           |        Y        |
|-----------------|-----------------|-----------------|
| [1, 0.3, 0.5]   | [0.7, 0.5, 0.3] | [0.4, 0.3, 0.6] |
| [0.7, 0.5, 0.3] | [0.4, 0.3, 0.6] | [0.1, 0.2, 0.3] |
| [0.4, 0.3, 0.1] | [0.1, 0.2, 0.3] | [0.4, 0.1, 0.4] |
| [0.1, 0.2, 0.3] | [0.4, 0.3, 0.6] | [0.2, 0.1, 0.2] |

En la fase de operación (después de entrenar) introducir 2 palabras y predecir la 3ra.

“El corpus grande se utiliza para aprender representaciones vectoriales, mientras que el ventaneo se utiliza para modelar relaciones secuenciales entre palabras.”

## CORPUS Y PRE-PROCESAMIENTO 

In [4]:
import sys
import os

# 1. Obtener la ruta de la carpeta raíz ("practicas") subiendo un nivel
ruta_raiz = os.path.abspath(os.path.join(os.getcwd(), '..'))

# 2. Agregar la ruta al inicio de la lista de búsqueda de Python
if ruta_raiz not in sys.path:
    sys.path.insert(0, ruta_raiz)

# 3. Importar la función desde el archivo funcion_preprocesamiento.py
# Reemplaza "tu_funcion" por el nombre real de tu función de preprocesamiento
from funcion_preprocesamiento import preprocesar_texto

# 4. Probar la función
# preprocesar_texto()

In [26]:
corpus = "La inteligencia artificial y el desarrollo de software están transformando la manera en que las personas interactúan con la tecnología. Actualmente, muchas empresas utilizan algoritmos de aprendizaje automático para analizar grandes cantidades de datos y automatizar procesos que antes requerían intervención humana. Además, el uso de computación en la nube permite almacenar información y ejecutar aplicaciones de manera más eficiente y segura. En el área de desarrollo web, lenguajes de programación como Python y JavaScript son ampliamente utilizados para crear aplicaciones modernas. También existen tecnologías relacionadas con ciberseguridad que ayudan a proteger sistemas informáticos contra ataques y robo de información. Por otro lado, los dispositivos móviles y el internet de las cosas han permitido conectar sensores, cámaras y otros equipos inteligentes a través de redes digitales. El avance tecnológico también ha impulsado la creación de robots, asistentes virtuales y plataformas de análisis de datos. Estas herramientas son utilizadas en sectores como educación, salud, finanzas e industria. Gracias a la innovación tecnológica, las computadoras pueden procesar información más rápido y resolver problemas complejos mediante modelos matemáticos y sistemas inteligentes."

In [27]:
# pre - procesamiento del corpus 
# mandar a llamar a la función de preprocesamiento
preprocesar_texto(corpus)


Texto después de limpiar (antes de stopwords): 'la inteligencia artificial y el desarrollo de software están transformando la manera en que las personas interactúan con la tecnología actualmente muchas empresas utilizan algoritmos de aprendizaje automático para analizar grandes cantidades de datos y automatizar procesos que antes requerían intervención humana además el uso de computación en la nube permite almacenar información y ejecutar aplicaciones de manera más eficiente y segura en el área de desarrollo web lenguajes de programación como python y javascript son ampliamente utilizados para crear aplicaciones modernas también existen tecnologías relacionadas con ciberseguridad que ayudan a proteger sistemas informáticos contra ataques y robo de información por otro lado los dispositivos móviles y el internet de las cosas han permitido conectar sensores cámaras y otros equipos inteligentes a través de redes digitales el avance tecnológico también ha impulsado la creación de robots as

['inteligencia',
 'artificial',
 'desarrollo',
 'software',
 'están',
 'transformando',
 'manera',
 'personas',
 'interactúan',
 'tecnología',
 'actualmente',
 'muchas',
 'empresas',
 'utilizan',
 'algoritmos',
 'aprendizaje',
 'automático',
 'analizar',
 'grandes',
 'cantidades',
 'datos',
 'automatizar',
 'procesos',
 'antes',
 'requerían',
 'intervención',
 'humana',
 'además',
 'uso',
 'computación',
 'nube',
 'permite',
 'almacenar',
 'información',
 'ejecutar',
 'aplicaciones',
 'manera',
 'más',
 'eficiente',
 'segura',
 'área',
 'desarrollo',
 'web',
 'lenguajes',
 'programación',
 'como',
 'python',
 'javascript',
 'ser',
 'ampliamente',
 'utilizados',
 'crear',
 'aplicaciones',
 'modernas',
 'también',
 'existen',
 'tecnologías',
 'relacionadas',
 'ciberseguridad',
 'ayudan',
 'proteger',
 'sistemas',
 'informáticos',
 'contra',
 'ataques',
 'robo',
 'información',
 'otro',
 'lado',
 'dispositivos',
 'móviles',
 'internet',
 'cosas',
 'han',
 'permitido',
 'conectar',
 'senso

In [28]:
import numpy as np

X = np.array([
    [1, 0.3, 0.5, 0.7, 0.5, 0.3],
    [0.7, 0.5, 0.3, 0.4, 0.3, 0.6],
    [0.4, 0.3, 0.1, 0.1, 0.2, 0.3],
    [0.1, 0.2, 0.3, 0.4, 0.3, 0.6]
])

Y = np.array([
    [0.4, 0.3, 0.6],
    [0.1, 0.2, 0.3],
    [0.4, 0.1, 0.4],
    [0.2, 0.1, 0.2]
])

## Red neuronal simple

In [29]:
# pesos iniciales
np.random.seed(0)
W = np.random.rand(6, 3)

# entrenamiento
lr = 0.01

for epoch in range(1000):
    # forward
    Y_pred = np.dot(X, W)
    
    # error
    error = Y - Y_pred
    
    # gradiente
    grad = np.dot(X.T, error)
    
    # actualizar pesos
    W += lr * grad

print("Pesos entrenados:")
print(W)

Pesos entrenados:
[[ 0.03327708 -0.07003063  0.32048388]
 [ 0.31921508  0.27021114  0.23089565]
 [ 0.16093502  0.3485359   0.57546019]
 [-0.06445766  0.02270428 -0.03499016]
 [ 0.5155107   0.40554141 -0.14102657]
 [-0.15126359 -0.26655001 -0.0287102 ]]


In [30]:
# ejemplo: Hola + Mundo
entrada = np.array([[1, 0.3, 0.5, 0.7, 0.5, 0.3]])

pred = np.dot(entrada, W)

print("Predicción vectorial:")
print(pred)

Predicción vectorial:
[[0.37676502 0.32399936 0.5738632 ]]


### Clasificar la predicción

In [31]:
def coseno(a, b):
    return np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))

# diccionario palabra → vector
vocab = {
    "ESCOM": np.array([0.9, 0.3, 0.6]),
    "es": np.array([0.1, 0.2, 0.3]),
    "lugar": np.array([0.4, 0.1, 0.4]),
    "donde": np.array([0.2, 0.1, 0.2])
}

mejor = ""
mejor_sim = -1

for palabra in vocab:
    sim = coseno(pred[0], vocab[palabra])
    
    if sim > mejor_sim:
        mejor_sim = sim
        mejor = palabra

print("Palabra predicha:", mejor)

Palabra predicha: donde
