Fecha: 28/04/2026
Retome los ejercicios anteriores 

-Tome un corpus de 1800 a 2000 palabras, después de pre-procesar los datos, aplique un método de vectorización, reduzca dimensión y normalice los vectores.

- Realizar el siguiente ventaneo:
    -> Doc: Hola Mundo, ESCOM es un lugar donde dan los buenos días.
- Suponga los vectores 

|                                               |                     |
|-----------------------------------------------|---------------------|
|[1,0.3,0.5] [0.7, 0.5, 0.3] [0.4, 0.3, 0.6]    | Hola , Mundo, ESCOM |
|[0.1, 0.2, 0.3] [0.4, 0.1, 0.4] [0.2, 0.1, 0.2]| es lugar donde      |

- A través de una red neuronal arme la siguiente matriz, y entrene

|       X         |   -->           |        Y        |
|-----------------|-----------------|-----------------|
| [1, 0.3, 0.5]   | [0.7, 0.5, 0.3] | [0.4, 0.3, 0.6] |
| [0.7, 0.5, 0.3] | [0.4, 0.3, 0.6] | [0.1, 0.2, 0.3] |
| [0.4, 0.3, 0.1] | [0.1, 0.2, 0.3] | [0.4, 0.1, 0.4] |
| [0.1, 0.2, 0.3] | [0.4, 0.3, 0.6] | [0.2, 0.1, 0.2] |

En la fase de operación (después de entrenar) introducir 2 palabras y predecir la 3ra.

“El corpus grande se utiliza para aprender representaciones vectoriales, mientras que el ventaneo se utiliza para modelar relaciones secuenciales entre palabras.”

## CORPUS Y PRE-PROCESAMIENTO 

In [1]:
corpus = [
    "Caminando corriendo montando",
    "Esta película fue terrible y aburrida",
    "Los actores actuaron muy bien ",
    "No me gustaron las tramas fueron malas",
    "Excelente dirección y guion brillante"
] # Corpus de 1800 - 2000 palabras 

In [2]:
# pre - procesamiento del corpus 
# mandar a llamar a la función de preprocesamiento


In [3]:
import numpy as np

X = np.array([
    [1, 0.3, 0.5, 0.7, 0.5, 0.3],
    [0.7, 0.5, 0.3, 0.4, 0.3, 0.6],
    [0.4, 0.3, 0.1, 0.1, 0.2, 0.3],
    [0.1, 0.2, 0.3, 0.4, 0.3, 0.6]
])

Y = np.array([
    [0.4, 0.3, 0.6],
    [0.1, 0.2, 0.3],
    [0.4, 0.1, 0.4],
    [0.2, 0.1, 0.2]
])

## Red neuronal simple

In [4]:
# pesos iniciales
np.random.seed(0)
W = np.random.rand(6, 3)

# entrenamiento
lr = 0.01

for epoch in range(1000):
    # forward
    Y_pred = np.dot(X, W)
    
    # error
    error = Y - Y_pred
    
    # gradiente
    grad = np.dot(X.T, error)
    
    # actualizar pesos
    W += lr * grad

print("Pesos entrenados:")
print(W)

Pesos entrenados:
[[ 0.03327708 -0.07003063  0.32048388]
 [ 0.31921508  0.27021114  0.23089565]
 [ 0.16093502  0.3485359   0.57546019]
 [-0.06445766  0.02270428 -0.03499016]
 [ 0.5155107   0.40554141 -0.14102657]
 [-0.15126359 -0.26655001 -0.0287102 ]]


In [5]:
# ejemplo: Hola + Mundo
entrada = np.array([[1, 0.3, 0.5, 0.7, 0.5, 0.3]])

pred = np.dot(entrada, W)

print("Predicción vectorial:")
print(pred)

Predicción vectorial:
[[0.37676502 0.32399936 0.5738632 ]]


### Clasificar la predicción

In [6]:
def coseno(a, b):
    return np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))

# diccionario palabra → vector
vocab = {
    "ESCOM": np.array([0.9, 0.3, 0.6]),
    "es": np.array([0.1, 0.2, 0.3]),
    "lugar": np.array([0.4, 0.1, 0.4]),
    "donde": np.array([0.2, 0.1, 0.2])
}

mejor = ""
mejor_sim = -1

for palabra in vocab:
    sim = coseno(pred[0], vocab[palabra])
    
    if sim > mejor_sim:
        mejor_sim = sim
        mejor = palabra

print("Palabra predicha:", mejor)

Palabra predicha: donde
