# Equipo Acevedo
Fecha: Abril 2026
Integrantes: 
- Fernanda Madariaga Villanueva
- Jared Trejo Medina
- José Eduardo Pérez Castillo
- Cebastian Acevedo Juares
- Derek Rodriguez Cruz

1. Preprocesamiento
    a. Tokenización + Eliminación de ruido + eliminación de signos de puntuación: Fe@rn12a_nd*a
    c. conversión a minusculas  
    e. removedor de stopwords
        I) Removedor de stopwords de acuerdo al tema. 
    f. lematización
3. Aplicar bag of words 

### Corpus y lectura de los documentos

In [40]:
# Aquí ira el corpus con las clases, referenciaremos documentos en la ruta Practicas/BagOfWords/
import os # para poder leer los documentos

# Función para leer el contenido de un documento
def leer_documento(path):
    with open(path, "r", encoding="utf-8") as f:
        return f.read()

# Corpues con los documentos y sus respectivas clases
corpus = [
    ("doc1.txt", leer_documento("doc1.txt"), "politica"),
    ("doc2.txt", leer_documento("doc2.txt"), "politica"),
    ("doc3.txt", leer_documento("doc3.txt"), "deportes"),
    ("doc4.txt", leer_documento("doc4.txt"), "deportes"),
    ("doc5.txt", leer_documento("doc5.txt"), "tecnologia"),
    ("doc6.txt", leer_documento("doc6.txt"), "tecnologia"),
    ("doc7.txt", leer_documento("doc7.txt"), "salud"),
    ("doc8.txt", leer_documento("doc8.txt"), "salud"),
    ("doc9.txt", leer_documento("doc9.txt"), "matemáticas"),
    ("doc10.txt", leer_documento("doc10.txt"), "matemáticas")
]

n_docs = len(corpus)
print(n_docs)

10


### Tokenizador + limpiador de texto + eliminación de signos de puntuación

In [41]:
# Tokenizador + limpiador del texto + eliminación de signos de puntuación
import string # para código ASCII

def tokenizador6(texto):
  texto_limpio = ""
  letras_permitidas = string.ascii_letters + "ñÑáéíóúÁÉÍÓÚ" + " "

  for caracter in texto:
    if caracter in letras_permitidas:
      texto_limpio += caracter

  print(f"Texto después de limpiar (antes de stopwords): '{texto_limpio}'")
  # considerando mayúsculas y espacios
  token = ""
  tokens = []

  for i in range(len(texto_limpio)):
    caracter = texto_limpio[i]
    # Si encontramos un espacio separamos
    if caracter == ' ':
      if token != "":
        tokens = tokens + [token]
        token = ""
    else:
      token += caracter

  # Agregar el último token si existe
  if token != "":
    tokens = tokens + [token]

  return tokens


### Conversión a minúsculas

In [42]:
# conversión a minusculas 
def A_minusculas(texto):
    letras = ""

    for letra in texto:
        if letra == 'e':
            pass
        if ord(letra) >= 65 and ord(letra) <=90:
            letra = chr(ord(letra) +32)
        letras += letra
    return letras

### Removedores de stopwords

Función de removedor de stopwords generales

In [43]:
# Removedor de stopwords general o removedor de stopwords de acuerdo al tema
def removedor_stop_words(tokenized_text):
    stop_words = ["de","la","que","el","en","y","a","los","del","se","las","por","un","para","con","una","su","al","lo"]
    new_text = []
    for item in tokenized_text:
        if item not in stop_words:
            new_text = new_text + [item]
    return new_text

### Contador de palabras


In [44]:
def count_words(text):
    count = 0
    withes = string.whitespace + '.'
    a_word = False

    for char in text:
        if char not in withes :
            if not a_word:
                count += 1
                a_word = True
        else:
            a_word = False

    return count

### Versiones de lematización

Aquí se referencia a un nuevo documento del cual no sabemos a que clase de texto pertenece, el cual tambien estará en la ruta PRACTICAS/BagOfWords/

In [45]:
lemmas_excepciones = {
    "fue":"ser",
    "fueron":"ser",
    "soy":"ser",
    "eres":"ser",
    "es":"ser",
    "estaba":"ser",
    "son":"ser",
    "malas":"malo",
    "malos":"malo",
    "buenas":"bueno",
    "peliculas":"pelicula",
    "actuaciones":"actuacion",
    "tramas":"trama",
    "mejores":"bueno",
    "era": "ser",
    "iba": "ir",
    "iban": "ir",
    "tuvo": "tener",
    "dijo" : "decir",
    "dijeron" : "decir",
    "dirán" : "decir",
    "hizo" : "hacer",
    "tuvo" : "tener",
    "árboles" : "árbol",
    "días" : "día"
}

diccionario_ar_gerundio = [
    "hablando", "cantando", "bailando", "saltando", "caminando","mirando", "escuchando", "pensando", "trabajando", "jugando",
    "estudiando", "viajando", "comprando", "pagando", "usando","tocando", "dibujando", "pintando", "imaginando", "recordando",
    "olvidando", "buscando", "llevando", "dejando", "guardando","explicando", "preguntando", "contestando", "cuidando", "ayudando",
    "intentando", "probando", "creando", "deseando", "esperando","logrando", "empezando", "terminando", "cambiando", "mejorando",
    "organizando", "planeando", "preparando", "presentando", "analizando","observando", "comparando", "señalando", "marcando", "considerando"
]

diccionario_ir_gerundio = [
    "viviendo","escribiendo","recibiendo","abriendo","permitiendo","admitiendo","asistiendo","dividiendo","decidiendo","repitiendo",
    "exigiendo","corrigiendo","dirigiendo","eligiendo","siguiendo","persiguiendo","consiguiendo","prohibiendo","imprimiendo","suprimiendo",
    "comprimiendo","expandiendo","confundiendo","difundiendo","fundiendo","hundiendo","interrumpiendo","cumpliendo","descubriendo","cubriendo",
    "inscribiendo","describiendo","suscribiendo","reescribiendo","proscribiendo","incluyendo","concluyendo","excluyendo","atribuyendo","distribuyendo",
    "retribuyendo","construyendo","destruyendo","instruyendo","sustituyendo","instituyendo","constituyendo","restituyendo","destituyendo","intuyendo","caminando"] #Verbos en infinitivo con termicación ir conjugados en gerundio

diccionario_er_gerundio = [
    "comiendo", "bebiendo", "leyendo", "corriendo", "temiendo","vendiendo", "aprendiendo", "entendiendo", "dependiendo", "sorbiendo",
    "mordiendo", "rompiendo", "respondiendo", "perdiendo", "volviendo","resolviendo", "envolviendo", "moviendo", "removiendo", "devolviendo",
    "cociendo", "torciendo", "retorciendo", "creciendo", "ofreciendo","mereciendo", "obedeciendo", "pareciendo", "estableciendo", "perteneciendo",
    "agradeciendo", "desapareciendo", "conociendo", "reconociendo", "traduciendo","produciendo", "reduciendo", "conduciendo", "introduciendo", "deduciendo",
    "seduciendo", "bendiciendo", "convenciendo", "venciendo", "defendiendo","encendiendo", "tendiendo", "extendiendo", "suspendiendo", "pretendiendo"
]

diccionario_ar_preterito = [
    "hablé", "hablaste", "habló", "hablamos", "hablaron",
    "canté", "cantaste", "cantó", "cantamos", "cantaron",
    "bailé", "bailaste", "bailó", "bailamos", "bailaron",
    "caminé", "caminaste", "caminó", "caminamos", "caminaron",
    "salté", "saltaste", "saltó", "saltamos", "saltaron",
    "miré", "miraste", "miró", "miramos", "miraron",
    "escuché", "escuchaste", "escuchó", "escuchamos", "escucharon",
    "trabajé", "trabajaste", "trabajó", "trabajamos", "trabajaron",
    "jugué", "jugaste", "jugó", "jugamos", "jugaron",
    "estudié", "estudiaste", "estudió", "estudiamos", "estudiaron",
    "viajé", "viajaste", "viajó", "viajamos", "viajaron",
    "compré", "compraste", "compró", "compramos", "compraron",
    "pagué", "pagaste", "pagó", "pagamos", "pagaron",
    "usé", "usaste", "usó", "usamos", "usaron",
    "toqué", "tocaste", "tocó", "tocamos", "tocaron",
    "dibujé", "dibujaste", "dibujó", "dibujamos", "dibujaron",
    "pinté", "pintaste", "pintó", "pintamos", "pintaron",
    "olvidé", "olvidaste", "olvidó", "olvidamos", "olvidaron",
    "busqué", "buscaste", "buscó", "buscamos", "buscaron",
    "ayudé", "ayudaste", "ayudó", "ayudamos", "ayudaron",
    "comencé", "comenzaste", "comenzó", "comenzamos", "comenzaron",
    "trabajé","trabajaste", "trabajó", "trabajamos", "trabajaron",
    "expliqué", "explicaste", "explicó", "explicamos", "explicaron",
    "cambié", "cambiaste", "cambió", "cambiamos", "cambiaron",
    "regresé", "regresaste", "regresó", "regresamos", "regresaron",
    "practiqué", "practicaste", "practicó", "practicamos", "practicaron",
    "preparé", "preparaste", "preparó", "preparamos", "prepararon",
    "organicé", "organizaste", "organizó", "organizamos", "organizaron",
    "terminé", "terminaste", "terminó", "terminamos", "terminaron",
    "mejoré", "mejoraste", "mejoró", "mejoramos", "mejoraron",
    "recordé", "recordaste", "recordó", "recordamos", "recordaron",
    "imaginé", "imaginaste", "imaginó", "imaginamos", "imaginaron",
    "pensé", "pensaste", "pensó", "pensamos", "pensaron"
]

diccionario_er_preterito = [
    "comí", "comiste", "comió", "comimos", "comieron",
    "bebí", "bebiste", "bebió", "bebimos", "bebieron",
    "corrí", "corriste", "corrió", "corrimos", "corrieron",
    "leí", "leíste", "leyó", "leímos", "leyeron",
    "temí", "temiste", "temió", "temimos", "temieron",
    "vendí", "vendiste", "vendió", "vendimos", "vendieron",
    "aprendí", "aprendiste", "aprendió", "aprendimos", "aprendieron",
    "entendí", "entendiste", "entendió", "entendimos", "entendieron",
    "dependí", "dependiste", "dependió", "dependimos", "dependieron",
    "sorbí", "sorbiste", "sorbió", "sorbimos", "sorbieron",
    "mordí", "mordiste", "mordió", "mordimos", "mordieron",
    "rompí", "rompiste", "rompió", "rompimos", "rompieron",
    "respondí", "respondiste", "respondió", "respondimos", "respondieron",
    "perdí", "perdiste", "perdió", "perdimos", "perdieron",
    "volví", "volviste", "volvió", "volvimos", "volvieron",
    "resolví", "resolviste", "resolvió", "resolvimos", "resolvieron",
    "moví", "moviste", "movió", "movimos", "movieron",
    "devolví", "devolviste", "devolvió", "devolvimos", "devolvieron",
    "torcí", "torciste", "torció", "torcimos", "torcieron",
    "ofrecí", "ofreciste", "ofreció", "ofrecimos", "ofrecieron",
    "respondí", "respondiste", "respondió", "respondimos", "respondieron",
    "nací", "naciste", "nació", "nacimos", "nacieron"
]

diccionario_ir_preterito = [
    "viví", "viviste", "vivió", "vivimos", "vivieron",
    "escribí", "escribiste", "escribió", "escribimos", "escribieron",
    "recibí", "recibiste", "recibió", "recibimos", "recibieron",
    "abrí", "abriste", "abrió", "abrimos", "abrieron",
    "permití", "permitiste", "permitió", "permitimos", "permitieron",
    "admití", "admitiste", "admitió", "admitimos", "admitieron",
    "asistí", "asististe", "asistió", "asistimos", "asistieron",
    "dividí", "dividiste", "dividió", "dividimos", "dividieron",
    "decidí", "decidiste", "decidió", "decidimos", "decidieron",
    "repetí", "repetiste", "repitió", "repetimos", "repitieron",
    "exigí", "exigiste", "exigió", "exigimos", "exigieron",
    "corrigí", "corregiste", "corrigió", "corregimos", "corrigieron",
    "dirigí", "dirigiste", "dirigió", "dirigimos", "dirigieron",
    "elegí", "elegiste", "eligió", "elegimos", "eligieron",
    "seguí", "seguiste", "siguió", "seguimos", "siguieron","seguía",
    "persiguí", "perseguiste", "persiguió", "perseguimos", "persiguieron",
    "conseguí", "conseguiste", "consiguió", "conseguimos", "consiguieron",
    "prohibí", "prohibiste", "prohibió", "prohibimos", "prohibieron",
    "imprimí", "imprimiste", "imprimió", "imprimimos", "imprimieron",
    "descubrí", "descubriste", "descubrió", "descubrimos", "descubrieron",
]

diccionario_ar_futuro = [
"hablaré","hablarás","hablará","hablaremos","hablarán",
"cantaré","cantarás","cantará","cantaremos","cantarán",
"bailaré","bailarás","bailará","bailaremos","bailarán",
"caminaré","caminarás","caminará","caminaremos","caminarán",
"saltaré","saltarás","saltará","saltaremos","saltarán",
"miraré","mirarás","mirará","miraremos","mirarán",
"escucharé","escucharás","escuchará","escucharemos","escucharán",
"trabajaré","trabajarás","trabajará","trabajaremos","trabajarán",
"jugaré","jugarás","jugará","jugaremos","jugarán",
"estudiaré","estudiarás","estudiará","estudiaremos","estudiarán",
"viajaré","viajarás","viajará","viajaremos","viajarán",
"compraré","comprarás","comprará","compraremos","comprarán",
"pagaré","pagarás","pagará","pagaremos","pagarán",
"usaré","usarás","usará","usaremos","usarán",
"tocaré","tocarás","tocará","tocaremos","tocarán",
"dibujaré","dibujarás","dibujará","dibujaremos","dibujarán",
"pintaré","pintarás","pintará","pintaremos","pintarán",
"buscaré","buscarás","buscará","buscaremos","buscarán",
"ayudaré","ayudarás","ayudará","ayudaremos","ayudarán",
"intentaré","intentarás","intentará","intentaremos","intentarán"
]

diccionario_er_futuro = [
"comeré","comerás","comerá","comeremos","comerán",
"beberé","beberás","beberá","beberemos","beberán",
"correré","correrás","correrá","correremos","correrán",
"leeré","leerás","leerá","leeremos","leerán",
"temeré","temerás","temerá","temeremos","temerán",
"venderé","venderás","venderá","venderemos","venderán",
"aprenderé","aprenderás","aprenderá","aprenderemos","aprenderán",
"entenderé","entenderás","entenderá","entenderemos","entenderán",
"dependeré","dependerás","dependerá","dependeremos","dependerán",
"morderé","morderás","morderá","morderemos","morderán",
"romperé","romperás","romperá","romperemos","romperán",
"responderé","responderás","responderá","responderemos","responderán",
"perderé","perderás","perderá","perderemos","perderán",
"volveré","volverás","volverá","volveremos","volverán",
"resolveré","resolverás","resolverá","resolveremos","resolverán",
"moveré","moverás","moverá","moveremos","moverán",
"devolveré","devolverás","devolverá","devolveremos","devolverán",
"torceré","torcerás","torcerá","torceremos","torcerán",
"ofreceré","ofrecerás","ofrecerá","ofreceremos","ofrecerán",
"temeré","temerás","temerá","temeremos","temerán"
]

diccionario_ir_futuro = [
"viviré","vivirás","vivirá","viviremos","vivirán",
"escribiré","escribirás","escribirá","escribiremos","escribirán",
"recibiré","recibirás","recibirá","recibiremos","recibirán",
"abriré","abrirás","abrirá","abriremos","abrirán",
"permitiré","permitirás","permitirá","permitiremos","permitirán",
"admitiré","admitirás","admitirá","admitiremos","admitirán",
"asistiré","asistirás","asistirá","asistiremos","asistirán",
"dividiré","dividirás","dividirá","dividiremos","dividirán",
"decidiré","decidirás","decidirá","decidiremos","decidirán",
"repetiré","repetirás","repetirá","repetiremos","repetirán",
"exigiré","exigirás","exigirá","exigiremos","exigirán",
"corregiré","corregirás","corregirá","corregiremos","corregirán",
"dirigiré","dirigirás","dirigirá","dirigiremos","dirigirán",
"elegiré","elegirás","elegirá","elegiremos","elegirán",
"seguiré","seguirás","seguirá","seguiremos","seguirán",
"perseguiré","perseguirás","perseguirá","perseguiremos","perseguirán",
"conseguiré","conseguirás","conseguirá","conseguiremos","conseguirán",
"prohibiré","prohibirás","prohibirá","prohibiremos","prohibirán",
"imprimiré","imprimirás","imprimirá","imprimiremos","imprimirán",
"descubriré","descubrirás","descubrirá","descubriremos","descubrirán"
]

def grammar_rules(word):
    n = len(word)
    
    if word[n-4:] == "ando" and word in diccionario_ar_gerundio:
        return word[:n-4] + "ar"
    if word[n-5:] == "iendo" and word in diccionario_ir_gerundio:
        return word[:n-5] + "ir"
    if word[n-5:] == "iendo" and word in diccionario_er_gerundio:
        return word[:n-5] + "er"

    # Pasado -ar
    if word[n-1:] == "é" and word in diccionario_ar_preterito:
        return word[:n-1] + "ar"
    if word[n-4:] == "aste" and word in diccionario_ar_preterito:
        return word[:n-4] + "ar"
    if word[n-1:] == "ó" and word in diccionario_ar_preterito:
        return word[:n-1] + "ar"
    if word[n-4:] == "amos" and word in diccionario_ar_preterito:
        return word[:n-4] + "ar"
    if word[n-4:] == "aron" and word in diccionario_ar_preterito:
        return word[:n-4] + "ar"

    # Pasado -er
    if word[n-1:] == "í" and word in diccionario_er_preterito:
        return word[:n-1] + "er"
    if word[n-2:] == "ía" and word in diccionario_er_preterito:
        return word[:n-2] + "er"
    if word[n-4:] == "iste" and word in diccionario_er_preterito:
        return word[:n-4] + "er"
    if word[n-2:] == "ió" and word in diccionario_er_preterito:
        return word[:n-2] + "er"
    if word[n-4:] == "imos" and word in diccionario_er_preterito:
        return word[:n-4] + "er"
    if word[n-5:] == "ieron" and word in diccionario_er_preterito:
        return word[:n-5] + "er"

    # Pasado -ir
    if word[n-1:] == "í" and word in diccionario_ir_preterito:
        return word[:n-1] + "ir"
    if word[n-2:] == "ía" and word in diccionario_ir_preterito:
        return word[:n-2] + "ir"
    if word[n-4:] == "iste" and word in diccionario_ir_preterito:
        return word[:n-4] + "ir"
    if word[n-2:] == "ió" and word in diccionario_ir_preterito:
        return word[:n-2] + "ir"
    if word[n-4:] == "imos" and word in diccionario_ir_preterito:
        return word[:n-4] + "ir"
    if word[n-5:] == "ieron" and word in diccionario_ir_preterito:
        return word[:n-5] + "ir"

    # Futuro -ar
    if word[-1:] == "é" and word in diccionario_ar_futuro:
        return word[:-1]
    if word[-2:] == "ás" and word in diccionario_ar_futuro:
        return word[:-2]
    if word[-1:] == "á" and word in diccionario_ar_futuro:
        return word[:-1]
    if word[-4:] == "emos" and word in diccionario_ar_futuro:
        return word[:-4]
    if word[-2:] == "án" and word in diccionario_ar_futuro:
        return word[:-2]

    # Futuro -er
    if word[-1:] == "é" and word in diccionario_er_futuro:
        return word[:-1]
    if word[-2:] == "ás" and word in diccionario_er_futuro:
        return word[:-2]
    if word[-1:] == "á" and word in diccionario_er_futuro:
        return word[:-1]
    if word[-4:] == "emos" and word in diccionario_er_futuro:
        return word[:-4]
    if word[-2:] == "án" and word in diccionario_er_futuro:
        return word[:-2]

    # Futuro -ir
    if word[-1:] == "é" and word in diccionario_ir_futuro:
        return word[:-1]
    if word[-2:] == "ás" and word in diccionario_ir_futuro:
        return word[:-2]
    if word[-1:] == "á" and word in diccionario_ir_futuro:
        return word[:-1]
    if word[-4:] == "emos" and word in diccionario_ir_futuro:
        return word[:-4]
    if word[-2:] == "án" and word in diccionario_ir_futuro:
        return word[:-2]
    

def lematizador1(corpus):
    lematized_words = []
    for word in corpus:
        lematized_word = grammar_rules(word)
        if lematized_word == None and word in lemmas_excepciones:
            lematized_word = lemmas_excepciones[word]
        elif lematized_word == None and word not in lemmas_excepciones:
            lematized_word = word
        lematized_words += [lematized_word]
    return lematized_words

# PRE Y PROCESAMIENTO DEL CORPUS

In [46]:
def preprocesar_texto(texto):
    # 1. minúsculas
    texto = A_minusculas(texto)
    
    # 2. tokenización + limpieza
    tokens = tokenizador6(texto)
    
    # 3. stopwords
    tokens = removedor_stop_words(tokens)
    
    # 4. lematización
    tokens = lematizador1(tokens)
    
    return tokens

In [47]:
corpus_procesado = []

i = 0
while i < n_docs:
    path, texto, clase = corpus[i]
    
    tokens = preprocesar_texto(texto)
    
    corpus_procesado += [(tokens, clase)]
    i += 1

print(corpus_procesado[0])


Texto después de limpiar (antes de stopwords): ' discurso de vicente fox como candidato presidencial del panhoy más allá de las cifras se expresa la voluntad política de la sociedad de nuestro país libremente sin acarreos y con una profunda voluntad de cambio en la elección democrática de acuerdo a estatutos del candidato del pan a la presidencia de la repúblicaun partido que nunca ha pretendido acaparar ni manipular como otros sino ser el más consciente y comprometido con el cambio que méxico requiereamigos y amigasvengo con una gran emoción a compartir con ustedes esta fiesta ciudadana celebrada en todos los rincones del país por mi partido acción nacional y en la que hemos participado miles y miles de mexicanosal elegirme como candidato de nuestro partido a la presidencia de la república me conmueve profundamente el honor que me han otorgado el más importante de mi vida y que me ofrece la oportunidad de servir a mi país con la pasión con la que hace doce años me comprometí al acepta

In [48]:
vocabulario = []

i = 0
while i < len(corpus_procesado):
    tokens, _ = corpus_procesado[i]
    
    j = 0
    while j < len(tokens):
        palabra = tokens[j]
        
        # evitar duplicados
        existe = False
        k = 0
        while k < len(vocabulario):
            if vocabulario[k] == palabra:
                existe = True
                break
            k += 1
        
        if not existe:
            vocabulario += [palabra]
        
        j += 1
    
    i += 1

vocab_size = len(vocabulario)

print("Tamaño del vocabulario:", vocab_size)

Tamaño del vocabulario: 1742


In [49]:
matrix = []

i = 0
while i < n_docs:
    fila = [0] * vocab_size
    matrix += [fila]
    i += 1

In [50]:
## LLENAR MATRIZ
i = 0
while i < n_docs:
    tokens, _ = corpus_procesado[i]
    
    j = 0
    while j < len(tokens):
        palabra = tokens[j]
        
        k = 0
        while k < vocab_size:
            if vocabulario[k] == palabra:
                matrix[i][k] += 1
                break
            k += 1
        
        j += 1
    
    i += 1

In [51]:
# Imprimir resultados
print("\nDimensiones de la matriz BoW:")
print("Documentos:", n_docs)
print("Palabras:", vocab_size)

print("\nMatriz Bag of Words:")
i = 0
while i < n_docs:
    print(corpus[i][0], matrix[i])
    i += 1


Dimensiones de la matriz BoW:
Documentos: 10
Palabras: 1742

Matriz Bag of Words:
doc1.txt [1, 2, 1, 4, 3, 1, 1, 10, 2, 1, 1, 2, 2, 2, 3, 5, 1, 2, 1, 1, 4, 1, 1, 1, 1, 1, 3, 1, 4, 1, 9, 1, 1, 1, 1, 1, 1, 6, 2, 1, 4, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 4, 1, 4, 2, 2, 3, 1, 2, 1, 1, 2, 6, 1, 1, 2, 1, 1, 2, 2, 1, 4, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 4, 1, 1, 1, 2, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 6, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 7, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 4, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

# Main: Clasificación de nuevos documentos

In [52]:
nuevo_doc = "nuevo_doc.txt"
# Leemos el nuevo documento (extraemos el texto)

# Se Pre-procesa el nuevo documento
texto_new = leer_documento(nuevo_doc)
tokens_new = preprocesar_texto(texto_new)

# Vectoriza el nuevo documento con el modelo de Bag of Words
vector_new = [0] * vocab_size

i = 0
while i < len(tokens_new):
    palabra = tokens_new[i]
    
    j = 0
    while j < vocab_size:
        if vocabulario[j] == palabra:
            vector_new[j] += 1
            break
        j += 1
    
    i += 1

print("\nVector del nuevo documento:")
print(vector_new)


Texto después de limpiar (antes de stopwords): 'las matemáticas son una disciplina que estudia los números las cantidades y las relaciones entre distintos valores se apoyan en el uso de símbolos operaciones y reglas para representar y resolver problemas desde operaciones básicas hasta conceptos más avanzados las matemáticas permiten describir situaciones de manera clara y ordenada facilitando el análisis de información y la toma de decisionesen la aritmética se trabajan las operaciones fundamentales suma resta multiplicación y división estas operaciones permiten manipular números y resolver cálculos cotidianos por ejemplo sumar cantidades repartir elementos o calcular proporciones son actividades comunes que dependen de estas bases los números pueden ser enteros como   o  o decimales como  o  lo que amplía las posibilidades de representaciónel álgebra introduce el uso de letras para representar valores desconocidos estas letras llamadas variables permiten plantear ecuaciones que descri

### TF/DF

In [53]:
# Retomar la matriz del corpus y NO SE agregar la fila del nuevo documento
# matrix += [vector_new]
# n_docs += 1
print("\nNueva matriz BoW con el nuevo documento:")
i = 0   
while i < n_docs:
    if i < n_docs - 1:
        print(corpus[i][0], matrix[i])
    else:
        print(nuevo_doc, matrix[i])
    i += 1


Nueva matriz BoW con el nuevo documento:
doc1.txt [1, 2, 1, 4, 3, 1, 1, 10, 2, 1, 1, 2, 2, 2, 3, 5, 1, 2, 1, 1, 4, 1, 1, 1, 1, 1, 3, 1, 4, 1, 9, 1, 1, 1, 1, 1, 1, 6, 2, 1, 4, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 4, 1, 4, 2, 2, 3, 1, 2, 1, 1, 2, 6, 1, 1, 2, 1, 1, 2, 2, 1, 4, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 4, 1, 1, 1, 2, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 6, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 7, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 4, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [54]:
# Guardar en una matriz verdadera para normalizar y aplicar PCA
import numpy as np
matriz_numpy = np.array(matrix)
print("\nMatriz BoW en formato NumPy:")
print(matriz_numpy)

matriz_numpy.shape


Matriz BoW en formato NumPy:
[[1 2 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 1 1]]


(10, 1742)

### Normalizar y PCA

In [57]:
# SOLO UNA VEZ --------------- Entrenar todo con la parte de entrenamiento (10 documentos)
matriz_numpy = np.array(matrix)
from sklearn.preprocessing import normalize
matriz_normalizada = normalize(matriz_numpy, norm='l2')
from sklearn.decomposition import PCA
pca = PCA(n_components=3)
matriz_pca = pca.fit_transform(matriz_normalizada)

print("\nMatriz BoW después de PCA:")
print(matriz_pca)


Matriz BoW después de PCA:
[[-0.73930961  0.04695711  0.02467563]
 [-0.78053315  0.05928268  0.00183551]
 [ 0.16016038  0.3839947   0.08322924]
 [ 0.18781028  0.35278292  0.1349888 ]
 [ 0.21200778 -0.26550803  0.43292523]
 [ 0.18473672 -0.35469302  0.49085186]
 [ 0.25753197  0.36744411 -0.19449433]
 [ 0.27283332  0.34296008 -0.21629418]
 [ 0.14827317 -0.44624486 -0.37185757]
 [ 0.09648914 -0.4869757  -0.38586021]]


In [56]:
# vector_new ya lo tenemos
vector_new_np = np.array([vector_new])

# usar MISMA normalización
vector_new_norm = normalize(vector_new_np, norm='l2')

# usar MISMO PCA
vector_new_pca = pca.transform(vector_new_norm)

print(vector_new_pca)

[[ 0.00214074 -0.17651284 -0.12680247]]


### Similitud - coseno